# Site settings
author: Gabriel Blatstein
title: The Journey to Become a Data Scientist
header-img: img/home-bg.png
email: gblatstein@gmail.com
copyright_name: Gabriel Blatstein
description: > # this means to ignore newlines until "baseurl:"
  Gabe's Data Science Journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  gabertooth

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
